ads/urls.py
from django.urls import path, reverse_lazy
from . import views


app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('done/', views.AdDoneListView.as_view(), name='all_done'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('task/<int:pk>/done/', views.mark_task_done, name='mark_task_done'),
    path('ad/create', views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

home/urls.py
from django.urls import path
from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    #path('', TemplateView.as_view(template_name='home/main.html')),
    path('', include('home.urls')),
    path('ads/', include('ads.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path('hello/', include('hello.urls')),
    path('polls/', include('polls.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/4.2/ref/urls/#include

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.views.generic import TemplateView
from django.conf import settings

# Create your views here.

# This is a little complex because we need to detect when we are
# running in various configurations


class HomeView(TemplateView):
    template_name = 'home/main.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'installed': settings.INSTALLED_APPS,
            'my_statement': "Nice to see you!"
        })
        return context

    def say_welcome(self):
        return 'Welcome'

home/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>

<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>


<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

{% block head %} {% endblock %}

</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

home/templates/base_menu.html
{% extends 'base_bootstrap.html' %}
{% load app_tags %} <!-- see home/templatetags/app_tags.py  -->
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="border-radius:10px !important">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'ads:all' %}">{{ settings.APP_NAME }}</a>
    <ul class="navbar-nav">
      {% url 'ads:all' as x %}
      <li {% if request.get_full_path == x %}class="active"{% endif %}>
          <a class="nav-link" href="{% url 'ads:all' %}" role="button">GL</a></li>
    </ul>
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
      <li>
         <a class="nav-link" href="{% url 'ads:all' %}">All Tasks</a>
      </li>
      <li>
         <a class="nav-link" href="{% url 'ads:all_done' %}">Done Tasks</a>
      </li>
      <li>
         <a class="nav-link" href="{% url 'ads:ad_create' %}">Create Task</a>
      </li>
      <li class="nav-item dropdown">
         <a class="nav-link dropdown-toggle" href="#" id="rightnavDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">

        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="rightnavDropdown">
            <li><a class="dropdown-item" href="{% url 'logout' %}?next={% url 'ads:all' %}">Logout</a></li>
        </ul>
       </li>
       {% else %}
       <li class="nav-item"><a class="nav-link" href="{% url 'login' %}?next={% url 'ads:all' %}">Login</a></li>
       {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}