ads/urls.py
from django.urls import path, reverse_lazy
from . import views


app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('done/', views.AdDoneListView.as_view(), name='all_done'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('task/<int:pk>/done/', views.mark_task_done, name='mark_task_done'),
    path('ad/create', views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    #path('', TemplateView.as_view(template_name='home/main.html')),
    path('', include('home.urls')),
    path('ads/', include('ads.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path('hello/', include('hello.urls')),
    path('polls/', include('polls.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/4.2/ref/urls/#include

ads/models.py
# Create your models here.
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings
from tinymce.models import HTMLField
from django.db.models import Index

class Ad(models.Model) :
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    responsible = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='responsible'
    )
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Comment', related_name='comments_owned')
    # Favorites
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Fav', related_name='favorite_ads')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_done = models.BooleanField(default=False)

    # Shows up in the admin list
    def __str__(self):
        return self.title

    picture = models.BinaryField(null=True, blank=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, blank=True,
        help_text='The MIMEType of the file')


class Comment(models.Model) :
    text = HTMLField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15 : return self.text
        return self.text[:11] + ' ...'

class Fav(models.Model) :
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # https://docs.djangoproject.com/en/4.2/ref/models/options/#unique-together
    class Meta:
        indexes = [
        Index(fields=['ad', 'user']),
    ]


    def __str__(self) :
        return '%s likes %s'%(self.user.username, self.ad.title[:10])

ads/forms.py
from django import forms
from ads.models import Ad
from django.core.files.uploadedfile import InMemoryUploadedFile
from ads.humanize import naturalsize
from .models import Comment


class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'


    class Meta:
        model = Ad
        fields = ['title', 'text', 'responsible', 'picture']  # Picture is manual

    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")

    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()
            self.save_m2m()
        return instance

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

    #comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

# https://docs.djangoproject.com/en/4.2/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/4.2/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

ads/views.py
from collections import defaultdict

from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q, OuterRef, Subquery
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError
from django.utils.html import strip_tags

from ads.forms import CreateForm, CommentForm
from ads.models import Ad, Comment, Fav
from ads.owner import OwnerListView, OwnerDetailView, OwnerDeleteView


class AdListView(OwnerListView):
    model = Ad
    template_name = "ads/ad_list.html"

    def get_queryset(self, search_query=None):
        """
        Fetch ads based on a search query or return the most recent ads.
        """
        if search_query:
            query = Q(title__icontains=search_query)
            query.add(Q(text__icontains=search_query), Q.OR)
            query.add(Q(tags__name__in=[search_query]), Q.OR)
            return Ad.objects.filter(query).select_related().distinct().order_by('-updated_at')[:10]
        return Ad.objects.all().order_by('-updated_at')[:10]

    def get_favorites(self, user):
        """
        Fetch the IDs of the ads marked as favorites by the user.
        """
        if user.is_authenticated:
            rows = user.favorite_ads.values('id')
            return [row['id'] for row in rows]
        return []

    def get_grouped_tasks(self):
        """
        Group tasks (ads) by the responsible user's username and sort them by the last comment time.
        """
        grouped_tasks = defaultdict(list)
        latest_comment = Comment.objects.filter(ad=OuterRef('pk')).order_by('-updated_at')
        tasks = Ad.objects.annotate(
            last_comment_time=Subquery(latest_comment.values('updated_at')[:1]),
            last_comment_content=Subquery(latest_comment.values('text')[:1]),
            last_comment_owner=Subquery(latest_comment.values('owner__username')[:1])
        ).order_by('-last_comment_time')

        for task in tasks:
            task.last_comment_content = strip_tags(task.last_comment_content) if task.last_comment_content else ""
            grouped_tasks[task.responsible.username].append(task)
        return grouped_tasks

    def augment_ads(self, ads):
        """
        Add a human-readable timestamp (natural time) to each ad.
        """
        for ad in ads:
            ad.natural_updated = naturaltime(ad.updated_at)

    def get(self, request):
        """
        Handle GET requests and render the ad list view.
        """
        search_query = request.GET.get("search", False)
        ad_list = self.get_queryset(search_query)
        self.augment_ads(ad_list)
        favorites = self.get_favorites(request.user)
        grouped_tasks = self.get_grouped_tasks()

        ctx = {
            'ad_list': ad_list,
            'favorites': favorites,
            'search': search_query,
            'grouped_tasks': dict(grouped_tasks),  # Convert defaultdict to a regular dictionary
        }
        return render(request, self.template_name, ctx)


class AdDoneListView(OwnerListView):
    model = Ad
    template_name = "ads/all_done.html"

    def get_queryset(self):
        """
        Override the default queryset to include only completed tasks.
        """
        return Ad.objects.filter(is_done=True)


class AdDetailView(OwnerDetailView):
    model = Ad
    template_name = "ads/ad_detail.html"
    def get(self, request, pk) :
        x = get_object_or_404(Ad, id=pk)
        comments = Comment.objects.filter(ad=x).order_by('-updated_at')
        comment_form = CommentForm()
        context = { 'ad' : x, 'comments': comments, 'comment_form': comment_form }
        return render(request, self.template_name, context)


class AdCreateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:all')

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        pic = form.save(commit=False)
        pic.owner = self.request.user
        pic.save()
        form.save_m2m()

        return redirect(self.success_url)

class AdUpdateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:all')

    def get(self, request, pk):
        pic = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(instance=pic)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        pic = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=pic)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        pic = form.save(commit=False)
        pic.save()
        form.save_m2m()

        return redirect(self.success_url)


class AdDeleteView(OwnerDeleteView):
    model = Ad
    fields = ['title','price','text']

class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        f = get_object_or_404(Ad, id=pk)
        comment = Comment(text=request.POST['text'], owner=request.user, ad=f)
        comment.save()
        return redirect(reverse('ads:ad_detail', args=[pk]))

class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "ads/comment_delete.html"

def stream_file(request, pk):
    pic = get_object_or_404(Ad, id=pk)
    response = HttpResponse()
    response['Content-Type'] = pic.content_type
    response['Content-Length'] = len(pic.picture)
    response.write(pic.picture)
    return response

def mark_task_done(request, pk):
    task = get_object_or_404(Ad, pk=pk)
    if request.method == 'POST':
        task.is_done = True
        task.save()
    return redirect('ads:all')


@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        t = get_object_or_404(Ad, id=pk)
        fav = Fav(user=request.user, ad=t)
        try:
            fav.save()  # In case of duplicate key
        except IntegrityError:
            pass
        return HttpResponse("Favorite added 42")

@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        t = get_object_or_404(Ad, id=pk)
        try:
            Fav.objects.get(user=request.user, ad=t).delete()
        except Fav.DoesNotExist:
            pass

        return HttpResponse("Favorite deleted 42")

ads/templates/ads/ad_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Ad</h1>

<p>Are you sure you want to delete the article: {{ ad }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

ads/templates/ads/ad_detail.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/4.2/ref/contrib/humanize -->
{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% endblock %}
{% block content %}
{% if pic.content_type %}
<div id="overlay" class="overlay" style="text-align: center;"
   onclick="document.getElementById('overlay').style.display = 'none';" >
<img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'ads:ad_picture' ad.id %}">
</div>
{% endif %}
<span style="float: right;">
({{ pic.updated_at|naturaltime }})
{% if ad.owner == user %}
<a href="{% url 'ads:ad_update' ad.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'ads:ad_delete' ad.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h2>{{ ad.title }}</h2>
{% if ad.content_type %}
<img style="float:right; max-width:50%;" src="{% url 'ads:ad_picture' ad.id %}"
    onclick="document.getElementById('overlay').style.display = 'block';">
{% endif %}

<p>
<b>Task: {{ ad.text | safe }}</b>
</p>
</p>
<p>
<b>
Responsible: {{ ad.responsible }}
</b>
<p>
{% for comment in comments %}
<p> {{ comment.text | safe}} by {{ comment.owner.username }}
({{ comment.updated_at|date:"D, d M Y H:i" }})
<!--{% if user == comment.owner %}
<a href="{% url 'ads:ad_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
{% endif %}-->
</p>
{% endfor %}
{% if not ad.is_done %}
    {% if user.is_authenticated %}
        <br clear="all"/>
        <p>
        <form method="post" action="{% url 'ads:ad_comment_create' ad.id %}">
            {% csrf_token %}
            {{ comment_form.text }}  <!-- Explicitly render the text field -->
            <input type="submit" value="Add comment">
        </form>
        </p>
    {% endif %}

    {% if not ad.is_done and request.user == ad.owner%}
        <form method="post" action="{% url 'ads:mark_task_done' ad.id %}">
            {% csrf_token %}
            <button type="submit">Mark as Done</button>
        </form>
    {% endif %}
{% endif %}
</p>
<p>
<a href="{% url 'ads:all' %}">All ads</a>
</p>
<script src="/static/tinymce/tinymce.min.js"></script>
<script>
    tinymce.init({
        selector: 'textarea',  // Replace 'textarea' with your element selector, e.g., '#id_text'
        height: 200,
        plugins: 'advlist autolink lists link image charmap print preview anchor searchreplace visualblocks code fullscreen insertdatetime media table paste code help wordcount',
        toolbar: 'undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help',
    });
</script>

{% endblock %}

ads/templates/ads/ad_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'ads:all' %}';return false;">
  </form>
</p>
<!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
<script>
document.getElementById("upload_form").addEventListener("submit", function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = document.getElementById('id_{{ form.upload_field_name }}').files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}

ads/templates/ads/ad_list.html
{% extends "base_menu.html" %}
{% block content %}
<!--{% if user.is_authenticated %}-->
<!--<h3>Tasks</h3>-->
<!-- Search Bar -->
<div style="float:right">
<!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
<form>
  <input type="text" placeholder="Search.." name="search"
  {% if search %} value="{{ search }}" {% endif %}
  >
  <button type="submit"><i class="fa fa-search"></i></button>
<a href="{% url 'ads:all' %}"><i class="fa fa-undo"></i></a>
</form>
</div>
<p>
<!-- Ad List Section -->
<!--{% if ad_list %}-->
<!--<ul>-->
<!--  {% for ad in ad_list %}-->
<!--    <li>-->
<!--        <a href="{% url 'ads:ad_detail'  ad.id %}">{{ ad.title | capfirst }}</a>-->
<!--        {% if ad.owner == user %}-->
<!--        (<a href="{% url 'ads:ad_update' ad.id %}">Edit</a> |-->
<!--        <a href="{% url 'ads:ad_delete' ad.id %}">Delete</a>)-->
<!--        {% endif %}-->
        <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
<!--        <a href="#" onclick=-->
<!--            "favPost('{% url 'ads:ad_unfavorite' ad.id %}', {{ ad.id }} );return false;"-->
<!--            {% if ad.id not in favorites %} style="display: none;" {% endif %}-->
<!--            id="favorite_star_{{ad.id}}">-->
<!--        <span class="fa-stack" style="vertical-align: middle;">-->
<!--        <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>-->
<!--        <i class="fa fa-star-o fa-stack-1x"></i>-->
<!--        </span>-->
<!--        </a>-->
        <!-- the second href -->
<!--        <a href="#" onclick=-->
<!--             "favPost('{% url 'ads:ad_favorite' ad.id %}', {{ ad.id }} );return false;"-->
<!--            {% if ad.id in favorites %} style="display: none;" {% endif %}-->
<!--            id="unfavorite_star_{{ad.id}}">-->
<!--        <span class="fa-stack" style="vertical-align: middle;">-->
<!--        <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>-->
<!--        <i class="fa fa-star-o fa-stack-1x"></i>-->
<!--        </span>-->
<!--        </a>-->
<!--        <small>-->
<!--        <small>-->
<!--        {% if ad.owner.username %}-->
<!--            by {{ ad.owner.username }}-->
<!--        {% endif %}-->
        <!--{{ ad.natural_updated }}-->
<!--        {{ ad.updated_at|date:"D, d M Y H:i" }}-->
<!--        </small>-->
<!--        </small>-->
<!--    </li>-->
<!--  {% endfor %}-->
<!--</ul>-->
<!--{% else %}-->
<!--  <p>There are no ads in the database.</p>-->
<!--{% endif %}-->
<!--</p>-->
<!--<p>-->
<!--<a href="{% url 'ads:ad_create' %}">Add a Task</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'ads:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'ads:all' %}">Login</a>
{% endif %}-->
</p>
<!-- Grouped Tasks Section -->
{% for user, tasks in grouped_tasks.items %}
    <h3>Tasks for {{ user }}</h3>
    <ul>
        {% for task in tasks %}
            {% if not task.is_done %}
            <li>
                <a href="{% url 'ads:ad_detail'  task.id %}">{{ task.title | capfirst }} </a>
                {% if task.last_comment_content %}
                <small>
                    <small>
                          <br>&nbsp;&nbsp;&nbsp;&nbsp;
                        {{ task.last_comment_time|date:"d.m H:i" }}
                        &nbsp;&nbsp;&nbsp;&nbsp;
                        {{ task.last_comment_content }}
                        &nbsp;&nbsp;&nbsp;&nbsp;
                        by {{task.last_comment_owner}}
                    </small>
                </small>
                {% endif %}
            </li>
            {% endif %}
        {% endfor %}
    </ul>
{% endfor %}
<!--{% endif %}-->

<script>
function toggleInlineDisplay(star_id) {
    var elem = document.getElementById(star_id);
    if(window.getComputedStyle(elem).display == "inline") {
        elem.style.display = 'none';
        elem.dataset.previousDisplay = 'inline';
    } else if(window.getComputedStyle(elem).display == "block") {
        elem.style.display = 'none';
        elem.dataset.previousDisplay = 'block';
    } else {
        console.log('prev', elem.dataset.previousDisplay);
        if ( typeof elem.dataset.previousDisplay == 'string' ) {
            elem.style.display = elem.dataset.previousDisplay
        } else {
            elem.style.display = 'inline';
        }
    }
}

function favPost(url, thing_id) {
    console.log('POSTing to', url);
    fetch(url, { method: 'POST', body: '{}' } )
    .then((response) => {
        console.log(url, 'finished');
        toggleInlineDisplay("unfavorite_star_"+thing_id);
        toggleInlineDisplay("favorite_star_"+thing_id);
    }).catch((error) => {
        alert('Url failed with '+error+' '+url);
    });
}
</script>
{% endblock %}

ads/templates/ads/all_done.html
{% extends "base_menu.html" %}
{% block content %}

<h2>Completed Tasks</h2>
    {% for ad in object_list %}
       <p style ="background-color: LightGreen;"> <a href="{% url 'ads:ad_detail' ad.id %}">{{ ad.title | capfirst }}</a></p>
    {% endfor %}

{% endblock %}

ads/templates/ads/comment_delete.html
{% extends "base_bootstrap.html" %}
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete</p>
<p>{{ comment.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'ads:ad_detail' comment.ad.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}